### ISSUE TITLE
Could not install the BoostForest by pip.

### ISSUE THREAD

**Issue by heartk-zero** [zhaochangming/BoostForest#1]
The BoostForest is an innovative work. But I can not install the BoostForest by pip. And I didn't find the BoostForest in Pipy.

When I try to install the BoostForest by pip:
_ERROR: Could not find a version that satisfies the requirement BoostForest (from versions: none)
ERROR: No matching distribution found for BoostForest_

Solved

**Comment by zhaochangming** [comment]
Thank you for your interest in BoostForest. We will upload BooostForest to pip in the future. Before that, you can download the zip package of BoostForest and run Demo.ipynb to show the demo result. Thanks!
